import traceback

# try:
#     raise Exception("This is the error message")
# except:
#     with open('errorLog.txt', 'a') as errorFile:
#         errorFile.write(traceback.format_exc())
#         print("The traceback info was written.")


# ----------- assert -------------
assert False, 'This is the next error'